# Unsupervised Learning Notes

## Key Terms:

- find structure in data without lables: unsupervised
- find patterns: clustering
- finding single line: dimensionality reduction

### K-Means:

#### Steps:
- <b/>Assign:</b> center points are placed in the middle of the data distribution
- <b/>Optimize:</b> minimumize cardinal distances between points
    - in this step, the centers assigned in step 1 are moved so the total distance between the assigned points and the placed center is minimized
    
- Initial poisitioning of centroids is important yet random, can get different results based on where the centroids were placed even if have the same number (ex. 2 centroids)

#### Key Parameters
- max_iter: the max times the model runs iterations 
- <b/>n_clusters: how many clusters you think is best for the model</b>
- n_init: num of times the model will be run using different seeds. This controls for the varying results when randomly placing center points at beginning

#### Overview
- can get counter-intuitive clusters based on placement of initial points
- "hill climbing" algorithm
- <b/>local minimum</b>: the seperation line between classes
    - get get non-optimal results, so must run algorithm multiple times

#### Resources:

- https://www.naftaliharris.com/blog/visualizing-k-means-clustering/
- http://scikit-learn.org/stable/modules/generated/sklearn.cluster.KMeans.html

#### Example Code

In [2]:
from sklearn.cluster import KMeans
import numpy as np

X = np.array([[1, 2], [1, 4], [1, 0],[4, 2], [4, 4], [4, 0]])

kmeans = KMeans(n_clusters=2, random_state=0).fit(X)

kmeans.labels_


array([0, 0, 0, 1, 1, 1], dtype=int32)

In [3]:
kmeans.predict([[0, 0], [4, 4]])


array([0, 1], dtype=int32)

In [4]:
kmeans.cluster_centers_


array([[ 1.,  2.],
       [ 4.,  2.]])